InsightSoftwareConsortium/ITKCuberille

circle.yml

The build times out.  The image should be built locally, then pushed to
DockerHub before a pull request.

BUG: Do not build the Docker image with CircleCI.

---

include/itkCuberilleImageToMeshFilter.h

Addresses:
/home/matt/src/ITK/Modules/Remote/Cuberille/include/itkCuberilleImageToMeshFilter.h: In instantiation of ‘class itk::CuberilleImageToMeshFilter<itk::Image<unsigned char, 3u>, itk::Mesh<unsigned char, 3u>, itk::LinearInterpolateImageFunction<itk::Image<unsigned char, 3u> > >’:
/home/matt/src/ITK/Modules/Remote/Cuberille/test/CuberilleTest01.cxx:123:16:   required from here
/home/matt/src/ITK/Modules/Core/Common/include/itkProcessObject.h:522:16: warning: ‘virtual void itk::ProcessObject::SetInput(const DataObjectIdentifierType&, itk::DataObject*)’ was hidden [-Woverloaded-virtual]
virtual void SetInput(const DataObjectIdentifierType & key, DataObject *input);
^
In file included from /home/matt/src/ITK/Modules/Remote/Cuberille/include/itkCuberilleImageToMeshFilter.h:347:0,
from …

COMP: Address SetInput override virtual warning.

---

CMakeLists.txt
include/itkCuberilleImageToMeshFilter.hxx

The fix could have been a bit more elegant of Normalize() returned the previous norm.

Fixing appearance of Not-A-Number values when gradient is 0

---

wrapping/itkCuberilleImageToMeshFilter.wrap

The old wrapping didn't work because the .wrap file did not include the superclass or fully specify the template.

BUG: Instatiate itkCuberilleImageToMeshFilter

---

include/itkCuberilleImageToMeshFilter.h
include/itkCuberilleImageToMeshFilter.hxx

Use initialization lists.
Remove the out-of-method-boduy, Doxygen method documentation from the
implementation file and put it to the method declarations in the header
file.
Print all member variables.
Make loop counter variables have a local scope.
Use brackets for one-liner control sentences.
Some other cosmetics: white spaces between variables and operators, etc.

STYLE: Improve the itk::CuberilleImageToMeshFilter style.

---

include/itkCuberilleImageToMeshFilter.hxx

The following compilation error is encountered when compiling with `c++14` in Ubuntu 16.04:
```
/home/davis/Developer/ITK/src/Modules/Remote/Cuberille/include/itkCuberilleImageToMeshFilter.hxx:79:32: error: ‘vnl_math_max’ was not declared in this scope
m_MaxSpacing = vnl_math_max( m_MaxSpacing, image->GetSpacing()[i] );
```
Similar errors are encountered for `vnl_math_abs`.

COMP: Prefer std to vnl_math

---

include/itkCuberilleImageToMeshFilter.h

Move `ITK_DISALLOW_COPY_AND_ASSIGN` calls to public section following
the discussion in
https://discourse.itk.org/t/noncopyable
If legacy (pre-macro) copy and assing methods existed, subsitute them
for the `ITK_DISALLOW_COPY_AND_ASSIGN` macro.

COMP: Move ITK_DISALLOW_COPY_AND_ASSIGN calls to public section.

---

include/itkCuberilleImageToMeshFilter.hxx
test/CMakeLists.txt
test/CuberilleTest02.cxx

Currently, the direction matrix of the input image is ignored
when computing the half-pixel offset in the AddVertex method.
When the direction matrix is identity, the result is correct;
in all other cases, the resulting mesh is shifted relative
to the underlying image data.  This small patch accounts for
the direction matrix in calculating the half-pixel offset, and
additionally adds a simple test for cases where the direction
matrix is non-identity.

BUG: Use Direction When Computing Offsets

---

include/itkCuberilleImageToMeshFilter.h
include/itkCuberilleImageToMeshFilter.hxx
test/CMakeLists.txt
test/CuberilleTest03.cxx

When a mesh is derived from a segmentation image, it is frequently useful
to know, for each cell in the mesh, the value of the adjacent pixel in
the segmentation image.  In this way, it is possible to extract a labeled
mesh from a multi-label segmentation.  This patch adds an option (off by
default) which allows the value of the adjacent pixel to be saved as cell
data.

ENH: Save Adjacent Pixel Value as Cell Data

---

include/itkCuberilleImageToMeshFilter.h
include/itkCuberilleImageToMeshFilter.hxx

This patch makes a number of small modernizations which should
marginally increase maintainability without impacting the logic
of the code.  In particular, std::array is prefered to c-style
arrays, and std::swap is preferred to a custom pre-processing
macro.

STYLE: Prefer std::array to c-style arrays

---

include/itkCuberilleImageToMeshFilter.h
include/itkCuberilleImageToMeshFilter.hxx
itk-module.cmake
test/CMakeLists.txt
test/CuberilleTest01.cxx

This patch addresses a long-standing issue in the Cuberille module
which frequently prevented its use with itk::QuadEdgeMesh, due a
number of cases in which this filter produces non-manifold geometry.
This patch determines, for each 2x2x2 neighborhood surrounding a
vertex, how many face-connected components N are present, and replicates
the relevant vertex N times.  Then, in the vertex map, the bitmask
and the position of the pixel index is used to determine which vertex
to select in the construction of each face.

BUG: Prevent Non-Manifold Geometry

---

include/itkCuberilleImageToMeshFilter.hxx
test/CMakeLists.txt
test/CuberilleTest01.cxx

There was a recent bugfix to the ITK connected components filter,
which is useed to generate the hardcoded connected components array.
Unfortunately, the array was generated with the filter prior to
applying the most recent ITK patch.  This filter regenerates the array.
Additionally, it updates to the correct number of points for the test
cases.  Finally, it enables itk::QuadEdgeMesh in the test suite,
verifying that the filter now works for this data type on all the
tested inputs.

BUG: Regenerate Hardcoded Array with CC Bugfix

---

README.rst

Fixes 404 error due to extraneous parenthesis.

BUG: Fix URL in License File

---

test/CuberilleTest01.cxx
test/CuberilleTest02.cxx
test/CuberilleTest03.cxx

This patch templatizes the primary test over the image and mesh type,
so that it can be run on both Mesh and QuadEdgeMesh.  Additionally,
ITK_TEST_SET_GET_BOOLEAN is preferred over ITK_TEST_SET_GET_VALUE
where appropriate.  Finally, consistent pixel and coordinate types
are used throughout. Line coverage is 99.8%, unchanged from prior to
the patch.  Function coverage is 98.0%, improved from 71.4% prior to
the patch.

ENH: Improve Code Coverage

---

.github/workflows/clang-format-linter.yml

Enforces ITK style, in keeping with the ITKModuleTemplate standard.

ENH: Add Clang Format Linter to Github Actions

---

include/itkCuberilleImageToMeshFilter.hxx
test/CMakeLists.txt
test/CuberilleTest04.cxx

itk::QuadEdgeMesh enforces manifold geometry, and therefore cases
where vertices appear at the same physical location must be handled
carefully.  A bugfix was recently applied which handles the vast
majority (252/256) of cases.  However, in the method fails in the
four possible cases where two background pixels appear at opposite
corners of a 2x2x2 region, with foreground pixels elsewhere.
This patch handles these four cases manually.  Testing and
documentation are updated as appropriate.

BUG: Handle Non-Manifold Geometry

---

include/itkCuberilleImageToMeshFilter.hxx
test/CuberilleTest04.cxx

This patch fixes an indexing error in case 231 (one of the four
"3D checkerboard" cases), which previously caused vertices to
be incorrectly linked.  The patch also expands the testing suite
to perform basic checks on all configurations around a vertex.

BUG: Fix Incorrect Indexing in Case 231

---

include/itkCuberilleImageToMeshFilter.h

This PR fixes changes made in [#2053](https://github.com/InsightSoftwareConsortium/ITK/pull/2053/commits/4eac1a0cfb456fad1e3894173a41d7c7de49b08f). Essentially, `ITK_DISALLOW_COPY_AND_ASSIGN` has been changed to `ITK_DISALLOW_COPY_AND_MOVE` to more accurately convey the actions taking place. `ITK_DISALLOW_COPY_AND_ASSIGN` will **only** be used if `ITK_FUTURE_LEGACY_REMOVE=OFF`.
**NOTE:** These changes will cause the GitHub Actions to break, because they currently build `ITK v5.1.0`. The errors persist with `v5.1.1` as well (will update to newest version in separate PR). When tested locally against `master`, I get all tests to pass. The case is the same for the remaining 39 remote modules.

STYLE: Rename ITK_DISALLOW_COPY_AND_ASSIGN to ITK_DISALLOW_COPY_AND_MOVE

---

include/itkCuberilleImageToMeshFilter.hxx

COMP: Remove inclusion of .hxx files as headers
The ability to include either .h or .hxx files as
header files required recursively reading the
.h files twice.  The added complexity is
unnecessary, costly, and can confuse static
analysis tools that monitor header guardes (due
to reaching the maximum depth of recursion
limits for nested #ifdefs in checking).

COMP: Remove inclusion of .hxx files as headers

---

.github/workflows/build-test-package.yml
include/itkCuberilleImageToMeshFilter.h
pyproject.toml
test/CuberilleTest01.cxx

Addresses libtbb Linux Python package issue:
https://github.com/InsightSoftwareConsortium/ITKPythonPackage/pull/291

COMP: Bump CI for ITK 5.4.2
